# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fe3ea34fd59c9491669b248a575c7e45fa12a320a0501d0364053a4b6d5d1e344a82a66c14c3afe70d4c35b1d2ac7fe2ba2ff63b5e5a1934506e7f32ceabacf

test:
  secret_key_base: 2addc7ee31a10b4fef6ec8f9882cf4f64f8f4214dd4c6e1e0ea4664a15cab110f5049b34b25cb086115b9845cedb1606d9a2c2c48b89614957debd9b3d500d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
